<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="CO5027_Asg.Admin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="addUserHeader"><h3>Manage User</h3></div>
    <div class="addformWrapper">


        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:db_1624980_db_1624980_user_db_1624980_co5027ConnectionString %>" DeleteCommand="DELETE FROM [AspNetUsers] WHERE [Id] = @original_Id AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND [UserName] = @original_UserName" InsertCommand="INSERT INTO [AspNetUsers] ([Id], [Email], [UserName]) VALUES (@Id, @Email, @UserName)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT [Id], [Email], [UserName] FROM [AspNetUsers]" UpdateCommand="UPDATE [AspNetUsers] SET [Email] = @Email, [UserName] = @UserName WHERE [Id] = @original_Id AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND [UserName] = @original_UserName">
            <DeleteParameters>
                <asp:Parameter Name="original_Id" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_UserName" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Id" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="UserName" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="UserName" Type="String" />
                <asp:Parameter Name="original_Id" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_UserName" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>

        <br />
        <asp:FormView ID="FormView1" runat="server" DataKeyNames="Product_ID" DataSourceID="SqlDataSource3" DefaultMode="Insert">
            <EditItemTemplate>
                Product_ID:
                <asp:Label ID="Product_IDLabel1" runat="server" Text='<%# Eval("Product_ID") %>' />
                <br />
                Product_name:
                <asp:TextBox ID="Product_nameTextBox" runat="server" Text='<%# Bind("Product_name") %>' />
                <br />
                Product_Description:
                <asp:TextBox ID="Product_DescriptionTextBox" runat="server" Text='<%# Bind("Product_Description") %>' />
                <br />
                Product_Quantity:
                <asp:TextBox ID="Product_QuantityTextBox" runat="server" Text='<%# Bind("Product_Quantity") %>' />
                <br />
                Price:
                <asp:TextBox ID="PriceTextBox" runat="server" Text='<%# Bind("Price") %>' />
                <br />
                <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update" Text="Update" />
                &nbsp;<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
            </EditItemTemplate>
            <InsertItemTemplate>
                Product_name:
                <asp:TextBox ID="Product_nameTextBox" runat="server" Text='<%# Bind("Product_name") %>' />
                <br />
                Product_Description:
                <asp:TextBox ID="Product_DescriptionTextBox" runat="server" Text='<%# Bind("Product_Description") %>' />
                <br />
                Product_Quantity:
                <asp:TextBox ID="Product_QuantityTextBox" runat="server" Text='<%# Bind("Product_Quantity") %>' />
                <br />
                Price:
                <asp:TextBox ID="PriceTextBox" runat="server" Text='<%# Bind("Price") %>' />
                <br />
                <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert" Text="Insert" />
                &nbsp;<asp:LinkButton ID="InsertCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
            </InsertItemTemplate>
            <ItemTemplate>
                Product_ID:
                <asp:Label ID="Product_IDLabel" runat="server" Text='<%# Eval("Product_ID") %>' />
                <br />
                Product_name:
                <asp:Label ID="Product_nameLabel" runat="server" Text='<%# Bind("Product_name") %>' />
                <br />
                Product_Description:
                <asp:Label ID="Product_DescriptionLabel" runat="server" Text='<%# Bind("Product_Description") %>' />
                <br />
                Product_Quantity:
                <asp:Label ID="Product_QuantityLabel" runat="server" Text='<%# Bind("Product_Quantity") %>' />
                <br />
                Price:
                <asp:Label ID="PriceLabel" runat="server" Text='<%# Bind("Price") %>' />
                <br />
                <asp:LinkButton ID="EditButton" runat="server" CausesValidation="False" CommandName="Edit" Text="Edit" />
                &nbsp;<asp:LinkButton ID="DeleteButton" runat="server" CausesValidation="False" CommandName="Delete" Text="Delete" />
                &nbsp;<asp:LinkButton ID="NewButton" runat="server" CausesValidation="False" CommandName="New" Text="New" />
            </ItemTemplate>
        </asp:FormView>
        <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:db_1624980_db_1624980_user_db_1624980_co5027ConnectionString %>" DeleteCommand="DELETE FROM [Product_tbl] WHERE [Product_ID] = @original_Product_ID AND (([Product_name] = @original_Product_name) OR ([Product_name] IS NULL AND @original_Product_name IS NULL)) AND (([Product_Description] = @original_Product_Description) OR ([Product_Description] IS NULL AND @original_Product_Description IS NULL)) AND (([Product_Quantity] = @original_Product_Quantity) OR ([Product_Quantity] IS NULL AND @original_Product_Quantity IS NULL)) AND (([Price] = @original_Price) OR ([Price] IS NULL AND @original_Price IS NULL))" InsertCommand="INSERT INTO [Product_tbl] ([Product_name], [Product_Description], [Product_Quantity], [Price]) VALUES (@Product_name, @Product_Description, @Product_Quantity, @Price)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Product_tbl]" UpdateCommand="UPDATE [Product_tbl] SET [Product_name] = @Product_name, [Product_Description] = @Product_Description, [Product_Quantity] = @Product_Quantity, [Price] = @Price WHERE [Product_ID] = @original_Product_ID AND (([Product_name] = @original_Product_name) OR ([Product_name] IS NULL AND @original_Product_name IS NULL)) AND (([Product_Description] = @original_Product_Description) OR ([Product_Description] IS NULL AND @original_Product_Description IS NULL)) AND (([Product_Quantity] = @original_Product_Quantity) OR ([Product_Quantity] IS NULL AND @original_Product_Quantity IS NULL)) AND (([Price] = @original_Price) OR ([Price] IS NULL AND @original_Price IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_Product_ID" Type="Int32" />
                <asp:Parameter Name="original_Product_name" Type="String" />
                <asp:Parameter Name="original_Product_Description" Type="String" />
                <asp:Parameter Name="original_Product_Quantity" Type="String" />
                <asp:Parameter Name="original_Price" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Product_name" Type="String" />
                <asp:Parameter Name="Product_Description" Type="String" />
                <asp:Parameter Name="Product_Quantity" Type="String" />
                <asp:Parameter Name="Price" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Product_name" Type="String" />
                <asp:Parameter Name="Product_Description" Type="String" />
                <asp:Parameter Name="Product_Quantity" Type="String" />
                <asp:Parameter Name="Price" Type="String" />
                <asp:Parameter Name="original_Product_ID" Type="Int32" />
                <asp:Parameter Name="original_Product_name" Type="String" />
                <asp:Parameter Name="original_Product_Description" Type="String" />
                <asp:Parameter Name="original_Product_Quantity" Type="String" />
                <asp:Parameter Name="original_Price" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>

        <br />
        <div class="ManageProdHeader">
            <h3>Manage Product</h3>
        </div>
        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="Product_ID" DataSourceID="SqlDataSource2" Width="704px">
            <Columns>
                <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
                <asp:BoundField DataField="Product_ID" HeaderText="Product_ID" InsertVisible="False" ReadOnly="True" SortExpression="Product_ID" />
                <asp:BoundField DataField="Product_name" HeaderText="Product_name" SortExpression="Product_name" />
                <asp:BoundField DataField="Product_Description" HeaderText="Product_Description" SortExpression="Product_Description" />
                <asp:BoundField DataField="Product_Quantity" HeaderText="Product_Quantity" SortExpression="Product_Quantity" />
                <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                <asp:HyperLinkField DataNavigateUrlFields="Product_ID" DataNavigateUrlFormatString="UploadProduct.aspx?id={0}" HeaderText="Upload" Text="Image" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:db_1624980_db_1624980_user_db_1624980_co5027ConnectionString %>" DeleteCommand="DELETE FROM [Product_tbl] WHERE [Product_ID] = @original_Product_ID AND (([Product_name] = @original_Product_name) OR ([Product_name] IS NULL AND @original_Product_name IS NULL)) AND (([Product_Description] = @original_Product_Description) OR ([Product_Description] IS NULL AND @original_Product_Description IS NULL)) AND (([Product_Quantity] = @original_Product_Quantity) OR ([Product_Quantity] IS NULL AND @original_Product_Quantity IS NULL)) AND (([Price] = @original_Price) OR ([Price] IS NULL AND @original_Price IS NULL))" InsertCommand="INSERT INTO [Product_tbl] ([Product_name], [Product_Description], [Product_Quantity], [Price]) VALUES (@Product_name, @Product_Description, @Product_Quantity, @Price)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Product_tbl]" UpdateCommand="UPDATE [Product_tbl] SET [Product_name] = @Product_name, [Product_Description] = @Product_Description, [Product_Quantity] = @Product_Quantity, [Price] = @Price WHERE [Product_ID] = @original_Product_ID AND (([Product_name] = @original_Product_name) OR ([Product_name] IS NULL AND @original_Product_name IS NULL)) AND (([Product_Description] = @original_Product_Description) OR ([Product_Description] IS NULL AND @original_Product_Description IS NULL)) AND (([Product_Quantity] = @original_Product_Quantity) OR ([Product_Quantity] IS NULL AND @original_Product_Quantity IS NULL)) AND (([Price] = @original_Price) OR ([Price] IS NULL AND @original_Price IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_Product_ID" Type="Int32" />
                <asp:Parameter Name="original_Product_name" Type="String" />
                <asp:Parameter Name="original_Product_Description" Type="String" />
                <asp:Parameter Name="original_Product_Quantity" Type="String" />
                <asp:Parameter Name="original_Price" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Product_name" Type="String" />
                <asp:Parameter Name="Product_Description" Type="String" />
                <asp:Parameter Name="Product_Quantity" Type="String" />
                <asp:Parameter Name="Price" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Product_name" Type="String" />
                <asp:Parameter Name="Product_Description" Type="String" />
                <asp:Parameter Name="Product_Quantity" Type="String" />
                <asp:Parameter Name="Price" Type="String" />
                <asp:Parameter Name="original_Product_ID" Type="Int32" />
                <asp:Parameter Name="original_Product_name" Type="String" />
                <asp:Parameter Name="original_Product_Description" Type="String" />
                <asp:Parameter Name="original_Product_Quantity" Type="String" />
                <asp:Parameter Name="original_Price" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Refresh" />
        <br />
        <br />
        <asp:SqlDataSource ID="SqlDataSource4" runat="server"></asp:SqlDataSource>
        <br />
</div>
</asp:Content>
