//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027_Asg
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage_tbl
    {
        public int Image_ID { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> Prod_Width { get; set; }
        public Nullable<int> Prod_Height { get; set; }
        public string Prod_Extension { get; set; }
        public string Image_Altenantetext { get; set; }
    }
}
