//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027_Asg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_tbl
    {
        public int Product_ID { get; set; }
        public string Product_name { get; set; }
        public string Product_Description { get; set; }
        public string Product_Quantity { get; set; }
        public string Price { get; set; }
    }
}
